#Tech Utilities Mod Config

# Disable or enable generation of the ores in the mod
generateCopper: true
generateTin: true
generateLead: true
generateSilver: true
generatePlatinum: true
generateNickel: true